name: parse_server_sdk
description: The Dart SDK to connect to Parse Server. Build your apps faster
  with Parse Platform, the complete application stack.
version: 6.1.0
homepage: https://parseplatform.org
repository: https://github.com/parse-community/Parse-SDK-Flutter
issue_tracker: https://github.com/parse-community/Parse-SDK-Flutter/issues
documentation: https://docs.parseplatform.org/dart/guide

funding:
  - https://opencollective.com/parse-server
  - https://github.com/sponsors/parse-community

topics:
  - parse
  - parse-platform
  - parse-server
  - node-js
  - backend

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  dio: ^5.4.3+1
  http: ^1.2.1
  meta: ^1.14.0
  mime_type: ^1.0.0
  path: ^1.9.0
  sembast: ^3.7.1+2
  sembast_web: ^2.4.0+2
  timezone: ^0.9.3
  universal_io: ^2.2.2
  uuid: ^4.4.0
  web: ^0.5.1
  web_socket_channel: ^3.0.0
  xxtea: ^2.1.0

dev_dependencies:
  # Testing
  build_runner: ^2.4.11
  lints: ^4.0.0
  mockito: ^5.4.4
  test: ^1.25.7

screenshots:
  - description: Parse Platform logo.
    path: screenshots/logo.png
